version: '3.1'

services:

  db:
    image: cassandra:3
    restart: always
    environment:
      POSTGRES_DB: studentdb
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
    ports:
      - 9042:9042
